### PR TITLE
Fixed issue: Error in pip install #70

### PR DESCRIPTION
**Pull request by norecces**
issue #70

### CODE REVIEW

**Comment by napjon** [comment]
Oh wow, what is it the character that technically caused the error? :)

All of this are running great, I see it can render all the notebooks. But it still failed the unit tests. I see only the last script, test_tooltip.py. Could you also fix that?

You can create the unit test environment by doing the following, 

```
pip install coverage pytest
git clone https://github.com/norecces/krisk
git checkout fix_pip_install_27
cd krisk
coverage run --source krisk -m py.test
```

I will also update the README.md to add the development mode, and python 2.7 in the CircleCI.

**Comment by norecces** [comment]
> Oh wow, what is it the character that technically caused the error? :)

yeap, that's it

> All of this are running great, I see it can render all the notebooks. But it still failed the unit tests. I see only the last script, test_tooltip.py. Could you also fix that?

done

thanks for nice lib !

**Review by napjon — APPROVED** [review]
LGTM

**Comment by napjon** [comment]
Merging. Thank you for contributing!

**Pull request merged**
